### ISSUE TITLE
resolution superbox has incorrect length

### ISSUE THREAD

**Issue by peterheb** [0xC0000054/pdn-jpeg-2000#1]
The JP2 files this plug-in is generating seem to be corrupt in a way that prevents some tools (like OpenJPEG) from being able to read them. Specifically, `opj_dump myfile.jp2` reports:

```
[ERROR] Cannot handle box of less than 8 bytes
[ERROR] Stream error while reading JP2 Header box
ERROR -> opj_dump: failed to read the header
```

Looking at the saved JP2 files in a hex editor, it looks to me like the 'res ' super-box is getting written to disk with a reported length of 0x00000014 when it should be 0x0000001a. Is that from upstream, or does this include a customized copy of JasPer?

**Comment by 0xC0000054** [comment]
> Is that from upstream, or does this include a customized copy of JasPer?

It is a customized version of JasPer, the upstream version does not support writing the image resolution.
